package apps;

import java.applet.Applet;

import global_data.GlobalViewData;
import graph.Edge;
import graph.Graph;
import graph.Node;
import views.meta.MainView;

public class TestApplet extends Applet {

	/**
	 * Generated By Eclipse
	 */
	private static final long serialVersionUID = -5057734514308341917L;

	@Override
	public void init() {
		super.init();
		Graph simple_graph = new Graph();
		Node n0 = simple_graph.addNode( new Node( "Dock", 20, 10 ) );
		Node n1 = simple_graph.addNode( new Node( "HBNet", 20, 30 ) );
		Edge e1 = simple_graph.addEdge( n0, n1 );

		e1.setColumnNameToSortBy( "total_score" );
		e1.setPercentageOfResultsToTransfer( 0.25 );
		e1.setUsePercentageInsteadOfCount( true );

		MainView view = new MainView( simple_graph );
		GlobalViewData.top_panel = view;

		this.add( view );
	}

	@Override
	public void start() {
		super.start();
	}

	@Override
	public void stop() {
		super.stop();
	}

	@Override
	public void destroy() {
		super.destroy();
	}

}
