package views;

import java.awt.BorderLayout;

import javax.swing.JPanel;
import javax.swing.JTextArea;

public class GraphViewWithInstructions extends JPanel {

	/**
	 * Generated By Eclipse
	 */
	private static final long serialVersionUID = 2678497215847049113L;
	
	private final GraphView graph_view_;
	private final JTextArea instrucitons_ = new JTextArea();
	
	public GraphViewWithInstructions(GraphView graph_view) {
		graph_view_ = graph_view;
		instrucitons_.setText( "Click: selects nodes and edges\n"
				+ "Ctrl + click: creates nodes\n"
				+ "Ctrl + click-and-drag: creates edges\n"
				+ "Shift + click: deletes nodes and edges\n\n"
				+ "Tip: edges need to be clicked on near their arrow,\n"
				+ "so try to prevent overlapping arrows from different edges" );
		instrucitons_.setEditable( false );
		
		this.setLayout( new BorderLayout() );
		this.add( graph_view_, BorderLayout.CENTER );
		this.add( instrucitons_, BorderLayout.SOUTH );
	}
	
}
