package views;

import java.awt.BorderLayout;
import java.awt.GridLayout;

import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JPanel;

public class SaveLoadView extends JPanel {

	/**
	 * Generated By Eclipse
	 */
	private static final long serialVersionUID = -9088179087599621175L;
	
	private final JFileChooser file_chooser_ = new JFileChooser();
	private final JButton save_button_ = new JButton( "Save" );
	private final JButton load_button_ = new JButton( "Load" );
	
	public SaveLoadView() {
		
		setLayout( new BorderLayout() );
		
		JPanel bottom_panel = new JPanel( new GridLayout( 1,3 ) );
		bottom_panel.add( save_button_ );
		bottom_panel.add( load_button_ );
		
		
		add( file_chooser_, BorderLayout.CENTER );
		add( bottom_panel, BorderLayout.SOUTH );
	}
	
}
