package views;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.JTextField;

public class SaveLoadView extends JPanel implements ActionListener, PropertyChangeListener {

	/**
	 * Generated By Eclipse
	 */
	private static final long serialVersionUID = -9088179087599621175L;
	
	private final JFileChooser file_chooser_ = new JFileChooser();
	private final JTextField load_path_field_ = new JTextField();
	private final JTextField load_filename_field_ = new JTextField( "pipeline.dat" );
	private final JButton save_button_ = new JButton( "Save" );
	
	public SaveLoadView() {
		
		setLayout( new BorderLayout() );
		
		file_chooser_.setApproveButtonText( "Load" );
		file_chooser_.addActionListener( this );
		
		file_chooser_.addPropertyChangeListener( this );
		load_path_field_.setText( file_chooser_.getCurrentDirectory().getName() );
		load_path_field_.setEditable( false );
		
		JPanel bottom_panel = new JPanel( new GridLayout( 1,3 ) );
		bottom_panel.add( load_path_field_ );
		bottom_panel.add( load_filename_field_ );
		bottom_panel.add( save_button_ );
		
		
		add( file_chooser_, BorderLayout.CENTER );
		add( bottom_panel, BorderLayout.SOUTH );
	}

	@Override
	public void actionPerformed( ActionEvent e ) {
    if (e.getActionCommand().equals(javax.swing.JFileChooser.APPROVE_SELECTION)) {
      System.out.println("approve selection");
    }
	}

	@Override
	public void propertyChange( PropertyChangeEvent evt ) {
		load_path_field_.setText( file_chooser_.getCurrentDirectory().getPath() + "/" );
	}
	
}
