package exceptions;

public class InvalidGraphException extends Exception {

	/**
	 * Generated By Eclipse
	 */
	private static final long serialVersionUID = 6280770730691291444L;

	public InvalidGraphException( String string ) {
		super( string );
	}

}
