package exceptions;

public class LoadFailureException extends Exception {

	/**
	 * Generated By Eclipse
	 */
	private static final long serialVersionUID = -1203678123039695628L;

	public LoadFailureException( String s ) {
		super( s );
	}

}
